FROM openjdk:8u161-nanoserver-sac2016
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop';"]

COPY . /src/
WORKDIR /src/
RUN	Setx path \"%path%;C:\Src\Python36;C:\Src\Python36\Scripts\"
RUN python -m pip install python-dateutil; \
	python -m pip install docker==3.2.1; \
	.\gradlew.bat shadow

WORKDIR /src/build/docker/
ENTRYPOINT ["java","-cp", "./ApplicationInsights-Docker-0.9.jar", "com.microsoft.applicationinsights.AgentBootstrapper"]
